NUM_PEGS : int = 3
NUM_DISKS : int = 3
NUM_BLOCKS : int = NUM_PEGS + NUM_DISKS

MAKE_GRAPHS = True
MAKE_CSV = True
MAKE_CORRELATION_ANALYSIS = False

REQUIRE_POSITIVE_GRADIENT_THRESHOLD = False
POSITIVE_GRADIENT_THRESHOLD = 0.04
REQUIRE_ANY_POSITIVE_NONZERO_GRADIENT = True

ALREADY_TRIED_THRESHOLD = 0.01